apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
  labels:
    release: monitoring
spec:
  route:
    repeatInterval: 30m
    receiver: 'null'
    routes:
    - matchers:
      - name: alertname
        value: HighCpuUsage
      receiver: 'send-email'
    - matchers:
      - name: alertname
        value: PodRestart
      receiver: 'send-email'
      repeatInterval: 5m
  receivers:
  - name: 'send-email'
    emailConfigs:
    - to: RECEIVER_EMAIL        # Where alerts are sent
      from: SENDER_EMAIL        # The email address of the sender
      smarthost: smtp.gmail.com:587
      authUsername: SENDER_EMAIL
      authIdentity: SENDER_EMAIL
      authPassword:
        name: mail-pass     # Name of the secret
        key: gmail-pass     # Key in the secret
      sendResolved: false
  - name: 'null'